dotFoods/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^wiki/', include('wikipage.urls', namespace='wikipage')),
    url(r'^wikiboto/', include('wikiboto.urls', namespace='wikiboto')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('search.urls', namespace='search')),
]

search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search_for, name='search_for'),
]

wikiboto/urls.py
from django.conf.urls import url

urlpatterns = [
]

wikipage/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<url_name>[^/]*)/$', views.show, name='show'),
]

search/models.py
from django.db import models

from dotFoods.settings import MAX_LEN_KEYWORD
from wikipage.models import WikiPage

class PageKeyword(models.Model):
    keyword = models.CharField(max_length=MAX_LEN_KEYWORD, db_index=True)
    count = models.FloatField()
    page = models.ForeignKey(WikiPage, db_index=True)

    def __str__(self):
        return self.keyword

wikiboto/models.py
from django.db import models

class BotoFinished(models.Model):
    url = models.CharField(primary_key=True, max_length=128, db_index=True)

    def __str__(self):
        return self.url

wikipage/models.py
from django.db import models

class WikiList(models.Model):
    url_name = models.CharField(primary_key=True, max_length=128, db_index=True)
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.url_name


class WikiPage(models.Model):
    url_name = models.CharField(primary_key=True, max_length=128, db_index=True)
    title = models.CharField(max_length=128)
    body = models.TextField(null=True)
    origin = models.URLField(null=True)
    lists = models.ManyToManyField("WikiList", db_index=True)
    categories = models.ManyToManyField("WikiCategory", db_index=True)

    def __str__(self):
        return self.url_name


class WikiCategory(models.Model):
    url_name = models.CharField(primary_key=True, max_length=128, db_index=True)
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.url_name

wikiboto/forms.py
from django import forms

class NewRootForm(forms.Form):
    new_root = forms.URLField(label='URL')
    depth = forms.IntegerField(min_value=1, max_value=10, label='Depth')

search/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from wikipage.models import WikiPage, WikiList, WikiCategory
from search.utils import tokenize

def index(request):
    return render(request, 'search/index.html')

def search_for(request):
    if 'q' not in request.GET:
        return HttpResponseRedirect('/')

    keywords = tokenize(request.GET['q'])
    if not keywords:
        return HttpResponseRedirect('/')

    pages = WikiPage.objects

    selected_lists = []
    # filter out lists if requested
    if 'lists' in request.POST:
        if request.POST.get('lists'):
            selected_lists = request.POST.get('lists').split(',')
            pages = pages.filter(lists__url_name__in=selected_lists)

    selected_categories = []
    # filter out categories if requested
    if 'categories' in request.POST:
        if request.POST.get('categories'):
            selected_categories = request.POST.get('categories').split(',')
            pages = pages.filter(categories__url_name__in=selected_categories)

    # filter out pages that do not match all the keywords
    for keyword in keywords:
        pages = pages.filter(pagekeyword__keyword=keyword)

    # use subquery to calculate the weight of result
    pages = pages.extra(select={
        'weight': 'SELECT SUM(count) ' +
                  'FROM search_pagekeyword ' +
                  'WHERE search_pagekeyword.page_id = ' +
                  'wikipage_wikipage.url_name AND ' +
                  'keyword in %s'},
        select_params=(tuple(keywords),),
    ).order_by('-weight')

    selected_lists_objects = \
        WikiList.objects.filter(url_name__in=selected_lists)
    selected_cates_objects = \
        WikiCategory.objects.filter(url_name__in=selected_categories)

    context = {
        'pages': pages.all(),
        'lists': WikiList.objects.order_by('title').all(),
        'selected_lists': selected_lists_objects,
        'categories': WikiCategory.objects.order_by('title').all(),
        'selected_cates': selected_cates_objects,
        'keyword': request.GET['q'],
    }

    template = 'search/results.html'
    if request.is_ajax():
        template = 'search/results_items.html'

    return render(request, template, context)

wikiboto/views.py
from django.shortcuts import render

wikipage/views.py
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect

from urllib.request import Request, urlopen
from urllib.parse import quote

from dotFoods import settings
from wikiboto.utils import can_access
from wikipage.models import \
    WikiList, WikiPage, WikiCategory

from bs4 import BeautifulSoup


def show(request, url_name):
    try:
        page = WikiPage.objects.get(url_name=url_name)
        return render(request, 'wikipage/show.html',
                      {'title': page.title,
                       'body': page.body,
                       'lists': page.lists,
                       'categories': page.categories})

    except ObjectDoesNotExist:
        url = "https://en.wikipedia.org/wiki/" + quote(url_name)
        if can_access(url):
            req = Request(
                url, data=None,
                headers={
                    'User-Agent': settings.USER_AGENT,
                })
            response = urlopen(req).read()
            page = BeautifulSoup(response, 'html.parser')
            title = str(page.find(id='firstHeading').string)
            body = page.find(id='bodyContent')
            for edits in body.find_all(class_='mw-editsection'):
                edits.extract()
            body.find(id='jump-to-nav').extract()
            return render(request, 'wikipage/show.html',
                          {'title': title,
                           'body': str(body)})
        else:
            return HttpResponseRedirect(url)

search/templates/search/index.html
{% extends 'base_site.html' %}
{% load staticfiles %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "homepage.css" %}">
{% endblock %}

{% block content %}
    <div class="search_container">
        <input id="search_box" type="text" name="search_for" title="Search" aria-label="Search" placeholder="Search"/>
    </div>
    <script src="{% static "jquery.js" %}"></script>
    <script>
        $('#search_box').keypress(function (e) {
            if (e.which == 13) {
                var encoded = encodeURIComponent($('#search_box')[0].value);
                window.location.href = "{% url 'search:search_for' %}?q=" + encoded;
            }
        });
    </script>
{% endblock %}

search/templates/search/results.html
{% extends 'base_site.html' %}
{% load staticfiles %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "results.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "token-input-facebook.css" %}">
{% endblock %}

{% block content %}
    <div id="list_filter">
        <form method="post" action="">
            {% csrf_token %}
            <div class="label"><label>Lists</label></div>
            <input type="text" id="lists" name="lists">
            <div class="label martop"><label>Categories</label></div>
            <input type="text" id="categories" name="categories">
            <input class="list_filter martop" type="submit" name="submit" value="Filter">
        </form>
    </div>

    <div class="search_container">
        <input id="search_box" type="text" name="search_for"
               title="Search" aria-label="Search" placeholder="Search"
               value="{{ keyword }}" />
    </div>

    <div id="search_results">
        {% include 'search/results_items.html' %}
    </div>

    <script src="{% static "jquery.js" %}"></script>
    <script src="{% static "jquery.tokeninput.js" %}"></script>
    <script src="{% static "endless_pagination/js/endless-pagination.js" %}"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollChunkSize: 5
        });

        $('#search_box').keypress(function (e) {
            if (e.which == 13) {
                var encoded = encodeURIComponent($('#search_box')[0].value);
                window.location.href = "{% url 'search:search_for' %}?q=" + encoded;
            }
        });
        $(document).ready(function() {
            $("#lists").tokenInput([
                {% for list in lists %}
                    {id: '{{ list.url_name }}', name: '{{ list.title }}'},
                {% endfor %}
            ] , {
                prePopulate: [
                    {% for list in selected_lists %}
                        {id: '{{ list.url_name }}', name: '{{ list.title }}'},
                    {% endfor %}
                ],
                theme: 'facebook',
                hintText: "Show foods in which lists?",
                preventDuplicates: true
            });

            $("#categories").tokenInput([
                {% for cat in categories %}
                    {id: '{{ cat.url_name }}', name: '{{ cat.title }}'},
                {% endfor %}
            ] , {
                prePopulate: [
                    {% for cat in selected_cates %}
                        {id: '{{ cat.url_name }}', name: '{{ cat.title }}'},
                    {% endfor %}
                ],
                theme: 'facebook',
                hintText: "Show foods in which categories?",
                preventDuplicates: true
            });
        });
    </script>
{% endblock %}

search/templates/search/results_items.html
{% load endless %}

{% lazy_paginate pages %}
{% for page in pages %}
    <div class="search_item">
        <div class="search_title">
            <a href="{% url 'wikipage:show' url_name=page.url_name %}">{{ page.title }}</a>
        </div>
        <div class="search_weight">
             <a>weight: {{ page.weight |floatformat:-3 }}</a>
        </div>
        <div class="search_origin">
            <a href="{{ page.origin }}">source: {{ page.origin }}</a>
        </div>
    </div>
{% empty %}
    <div class="endless_container">
        <a class="endless_loading" href="/">no results</a>
    </div>
{% endfor %}
{% show_more %}

templates/base_site.html
{% extends "admin/base.html" %}
{% load i18n staticfiles %}p

{% block title %}
    {% if title %}
    {{ title }}
    {% else %}
    {{ _('dotFoods') }}
    {% endif %}
{% endblock %}

{% block branding %}
    <h1 id="site-name"><a href="{% url 'search:index' %}">{{ _('dotFoods') }}</a></h1>
{% endblock %}

{% block usertools %}
    <div id="user-tools">
        {% trans 'Welcome, enjoy the foods.' %}
        {% comment %}
        <a href="{% url 'search:index' %}">{{ _('Search') }}</a> /
        <a href="">{{ _('Lists') }}</a> /
        <a href="">{{ _('Categories') }}</a>
        {% endcomment %}
    </div>
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

wikipage/templates/wikipage/show.html
{% extends 'base_site.html' %}
{% load staticfiles %}

{% block extrahead %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "vector.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "dotmin.css" %}">
{% endblock %}

{% block content %}
    <ul class="tags">
        {% for list in lists.all %}
            {% if forloop.counter == 1 %}
            <li><a class="fake_tag">{{ _('Lists') }}</a></li>
            {% endif %}
            <li><a class="tag">{{ list.title }}</a></li>
        {% endfor %}
    </ul>
    <ul class="tags">
        {% for cate in categories.all %}
            {% if forloop.counter == 1 %}
            <li><a class="fake_tag">{{ _('Categories') }}</a></li>
            {% endif %}
            <li><a class="tag">{{ cate.title }}</a></li>
        {% endfor %}
    </ul>
    <div id="hot_area"></div>
    {{ body | safe }}
{% endblock %}